# FROM zhiqzhao/ubuntu_weblogic1036_domain:latest
# FROM registry.cn-shanghai.aliyuncs.com/hellodock/weblogic10:latest
FROM registry.cn-shanghai.aliyuncs.com/hellodock/weblogic10_jdk7:latest

WORKDIR /root/Oracle/Middleware/user_projects/domains/base_domain

EXPOSE 7001 7002
