FROM registry.cn-shanghai.aliyuncs.com/hellodock/redhat:6.5.11.wls10.jdk7
WORKDIR /home/weblogic/Oracle/Middleware/user_projects/domains/base_domain

# FROM registry.cn-shanghai.aliyuncs.com/hellodock/redhat:6.5.11.wls10.jdk7.root
# WORKDIR /root/Oracle/Middleware/user_projects/domains/base_domain

# CMD ["./startWebLogic.sh"]

ENTRYPOINT ["./startWebLogic.sh"]

EXPOSE 7001
