# FROM store/oracle/weblogic:12.2.1.2
# FROM ismaleiva90/weblogic12
FROM registry.cn-shanghai.aliyuncs.com/hellodock/weblogic12

WORKDIR /u01/oracle/weblogic/user_projects/domains/base_domain

EXPOSE 7001 7002
