# FROM store/oracle/weblogic:12.2.1.2
FROM ismaleiva90/weblogic12

# COPY ./config/config.xml /u01/oracle/weblogic/user_projects/domains/base_domain/config/

WORKDIR /u01/oracle/weblogic/user_projects/domains/base_domain

EXPOSE 7001
