FROM idoall/ubuntu16.04-jira-software:7.12.3

# files
# COPY ./lib/ /opt/atlassian/jira/atlassian-jira/WEB-INF/lib/

WORKDIR /opt/atlassian/jira/atlassian-jira/WEB-INF/lib/

EXPOSE 8080 8005 8443 8090
