# FROM idoall/ubuntu16.04-jira-software:7.12.3
FROM registry.cn-shanghai.aliyuncs.com/hellodock/jira:7.12.3

# hack
# WORKDIR /usr/src/_jira/

WORKDIR /opt/atlassian/jira/atlassian-jira/WEB-INF/lib/

EXPOSE 8080 8005 8443 8090
